export const SuccessMessages = {
  REGISTER_SUCCESSFUL: 'Success.REGISTER_SUCCESSFUL',
  OTP_SENT: 'Success.OTP_SENT',

  NEED_2FA_VERIFICATION: 'Success.NEED_2FA_VERIFICATION',
  LOGIN_SUCCESSFUL: 'Success.LOGIN_SUCCESSFUL',
  REFRESH_TOKEN_SUCCESSFUL: 'Success.REFRESH_TOKEN_SUCCESSFUL',
  LOGOUT_SUCCESSFUL: 'Success.LOGOUT_SUCCESSFUL',
  GET_GOOGLE_LINK_SUCCESSFUL: 'Success.GET_GOOGLE_LINK_SUCCESSFUL',
  SET_UP_2FA_SUCCESSFUL: 'Success.SET_UP_2FA_SUCCESSFUL',
  DISABLE_2FA_SUCCESSFUL: 'Success.DISABLE_2FA_SUCCESSFUL',
} as const

export const ErrorMessages = {
  REQUIRED_REFRESH_TOKEN: 'Error.REQUIRED_REFRESH_TOKEN',
  INVALID_REFRESH_TOKEN: 'Error.INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_NOT_FOUND: 'Error.REFRESH_TOKEN_NOT_FOUND',
  DUPLICATE_REFRESH_TOKEN: 'Error.DUPLICATE_REFRESH_TOKEN',

  INVALID_OTP_CODE: 'Error.INVALID_OTP',
  EXPIRED_OTP_CODE: 'Error.EXPIRED_OTP',
  INVALID_VERIFICATION_CODE_TYPE: 'Error.INVALID_VERIFICATION_CODE_TYPE',

  NO_NEEDED_CODE_OR_TOTP: 'Error.NO_NEEDED_CODE_OR_TOTP',
  REQUIRED_ONE_OF_TOTP_OR_CODE: 'Error.REQUIRED_ONE_OF_CODE_OR_TOTP',
  ONLY_TOTP_OR_CODE: 'Error.ONLY_TOTP_OR_CODE',
  REQUIRED_TOTP_CODE: 'Error.REQUIRED_TOTP_CODE',
  INVALID_TOTP_CODE: 'Error.INVALID_TOTP_CODE',
  INVALID_TOTP_CODE_LENGTH: 'Error.INVALID_TOTP_CODE_LENGTH',

  TWO_FACTOR_AUTH_ALREADY_ENABLED: 'Error.TWO_FACTOR_AUTH_ALREADY_ENABLED',
  TWO_FACTOR_AUTH_NOT_ENABLED: 'Error.TWO_FACTOR_AUTH_NOT_ENABLED',

  EMAIL_ALREADY_EXISTS: 'Error.EMAIL_ALREADY_EXISTS',
  EMAIL_DOES_NOT_EXIST: 'Error.EMAIL_DOES_NOT_EXIST',
  EMAIL_OR_PASSWORD_INCORRECT: 'Error.EMAIL_OR_PASSWORD_INCORRECT',

  REQUIRED_GOOGLE_CODE: 'Error.REQUIRED_GOOGLE_CODE',
  INVALID_GOOGLE_CODE: 'Error.INVALID_GOOGLE_CODE',
  REQUIRED_GOOGLE_STATE: 'Error.REQUIRED_GOOGLE_STATE',
  INVALID_GOOGLE_STATE: 'Error.INVALID_GOOGLE_STATE',
  GENERIC_GOOGLE_CALLBACK: 'Error.GENERIC_GOOGLE_CALLBACK',
  MISSING_EMAIL_FROM_GOOGLE: 'Error.MISSING_EMAIL_FROM_GOOGLE',
} as const
