export const SuccessMessages = {
  REGISTER_SUCCESSFUL: 'Success.REGISTER_SUCCESSFUL',
  OTP_SENT: 'Success.OTP_SENT',
  LOGIN_SUCCESSFUL: 'Success.LOGIN_SUCCESSFUL',
  REFRESH_TOKEN_SUCCESSFUL: 'Success.REFRESH_TOKEN_SUCCESSFUL',
  LOGOUT_SUCCESSFUL: 'Success.LOGOUT_SUCCESSFUL',
  GET_GOOGLE_LINK_SUCCESSFUL: 'Success.GET_GOOGLE_LINK_SUCCESSFUL',
} as const

export const ErrorMessages = {
  GENERIC: 'Error.GENERIC',

  REQUIRED_TOKEN: 'Error.REQUIRED_TOKEN',
  INVALID_OTP: 'Error.INVALID_OTP',
  EXPIRED_OTP: 'Error.EXPIRED_OTP',

  EMAIL_ALREADY_EXISTS: 'Error.EMAIL_ALREADY_EXISTS',
  EMAIL_DOES_NOT_EXIST: 'Error.EMAIL_DOES_NOT_EXIST',
  EMAIL_OR_PASSWORD_INCORRECT: 'Error.EMAIL_OR_PASSWORD_INCORRECT',

  REFRESH_TOKEN_NOT_FOUND: 'Error.REFRESH_TOKEN_NOT_FOUND',
  DUPLICATE_REFRESH_TOKEN: 'Error.DUPLICATE_REFRESH_TOKEN',

  REQUIRED_GOOGLE_CODE: 'Error.REQUIRED_GOOGLE_CODE',
  INVALID_GOOGLE_CODE: 'Error.INVALID_GOOGLE_CODE',
  REQUIRED_GOOGLE_STATE: 'Error.REQUIRED_GOOGLE_STATE',
  INVALID_GOOGLE_STATE: 'Error.INVALID_GOOGLE_STATE',
  GENERIC_GOOGLE_CALLBACK: 'Error.GENERIC_GOOGLE_CALLBACK',
  MISSING_EMAIL_FROM_GOOGLE: 'Error.MISSING_EMAIL_FROM_GOOGLE',
} as const
