export const SuccessMessages = {
  GET_PROFILE_SUCCESSFULLY: 'Success.GET_PROFILE_SUCCESSFULLY',
  UPDATE_PROFILE_SUCCESSFULLY: 'Success.UPDATE_PROFILE_SUCCESSFULLY',
  CHANGE_PASSWORD_SUCCESSFULLY: 'Success.CHANGE_PASSWORD_SUCCESSFULLY',
} as const

export const ErrorMessages = {
  AVATAR_INVALID: 'Error.AVATAR_INVALID',
  PASSWORD_INCORRECT: 'Error.PASSWORD_INCORRECT',
} as const
