export const CommonErrorMessages = {
  ADDITIONAL_PROPERTIES_NOT_ALLOWED: 'Error.ADDITIONAL_PROPERTIES_NOT_ALLOWED',

  REQUIRED_NAME: 'Error.REQUIRED_NAME',
  INVALID_NAME_TYPE: 'Error.INVALID_NAME_TYPE',
  SHORT_NAME: 'Error.SHORT_NAME',
  LONG_NAME: 'Error.LONG_NAME',

  REQUIRED_EMAIL: 'Error.REQUIRED_EMAIL',
  INVALID_EMAIL_TYPE: 'Error.INVALID_EMAIL_TYPE',
  INVALID_EMAIL: 'Error.INVALID_EMAIL',

  REQUIRED_PHONE_NUMBER: 'Error.REQUIRED_PHONE_NUMBER',
  INVALID_PHONE_NUMBER: 'Error.INVALID_PHONE_NUMBER',

  REQUIRED_PASSWORD: 'Error.REQUIRED_PASSWORD',
  INVALID_PASSWORD: 'Error.INVALID_PASSWORD',
  SHORT_PASSWORD: 'Error.SHORT_PASSWORD',
  LONG_PASSWORD: 'Error.LONG_PASSWORD',

  REQUIRED_CONFIRM_PASSWORD: 'Error.REQUIRED_CONFIRM_PASSWORD',
  INVALID_CONFIRM_PASSWORD: 'Error.INVALID_CONFIRM_PASSWORD',
  SHORT_CONFIRM_PASSWORD: 'Error.SHORT_CONFIRM_PASSWORD',
  LONG_CONFIRM_PASSWORD: 'Error.LONG_CONFIRM_PASSWORD',
  PASSWORDS_DO_NOT_MATCH: 'Error.PASSWORDS_DO_NOT_MATCH',

  REQUIRED_CODE: 'Error.REQUIRED_CODE',
  INVALID_CODE: 'Error.INVALID_CODE',
  CODE_LENGTH: 'Error.CODE_LENGTH',
} as const
