export const SuccessMessages = {
  GET_PERMISSION_SUCCESSFUL: 'Success.GET_PERMISSION_SUCCESSFUL',
  GET_PERMISSIONS_SUCCESSFUL: 'Success.GET_PERMISSIONS_SUCCESSFUL',
  CREATE_PERMISSION_SUCCESSFUL: 'Success.CREATE_PERMISSION_SUCCESSFUL',
  UPDATE_PERMISSION_SUCCESSFUL: 'Success.UPDATE_PERMISSION_SUCCESSFUL',
  DELETE_PERMISSION_SUCCESSFUL: 'Success.DELETE_PERMISSION_SUCCESSFUL',
} as const

export const ErrorMessages = {
  PERMISSION_NOT_FOUND: 'Error.PERMISSION_NOT_FOUND',
  PERMISSION_ALREADY_EXISTS: 'Error.PERMISSION_ALREADY_EXISTS',

  PERMISSION_NAME_REQUIRED: 'Error.PERMISSION_NAME_REQUIRED',
  PERMISSION_NAME_INVALID: 'Error.PERMISSION_NAME_INVALID',
  PERMISSION_NAME_TOO_LONG: 'Error.PERMISSION_NAME_TOO_LONG',

  PERMISSION_DESCRIPTION_INVALID: 'Error.PERMISSION_DESCRIPTION_INVALID',

  PERMISSION_PATH_REQUIRED: 'Error.PERMISSION_PATH_REQUIRED',
  PERMISSION_PATH_INVALID: 'Error.PERMISSION_PATH_INVALID',
  PERMISSION_PATH_TOO_LONG: 'Error.PERMISSION_PATH_TOO_LONG',

  PERMISSION_METHOD_INVALID: 'Error.PERMISSION_METHOD_INVALID',

  PERMISSION_MODULE_INVALID: 'Error.PERMISSION_MODULE_INVALID',
  PERMISSION_MODULE_TOO_LONG: 'Error.PERMISSION_MODULE_TOO_LONG',
} as const
